### ISSUE TITLE
Compat issue with Fruitful - leaves waterlogged by default

### ISSUE THREAD

**Issue by ex0planetary** [Tfarcenim/MoreWaterlogging#5]
Hi, I'm the lead dev of [Fruitful](https://github.com/teamauroramods/fruitful). A few users of my mod have reported an issue with the mod's Blossoming Oak Leaves being waterlogged by default when this mod is installed. I did some digging and I'm pretty sure it's not anything on my end so I figured I'd submit a bug report to you.

I see that this mod makes leaves waterloggable - however, my guess is that it doesn't play well with LeavesBlocks that add new BooleanProperties. The thing that makes the Blossoming Oak Leaves different from all the other leaves in my mods is that it has a BooleanProperty that stores whether the block has been pollinated. Seeing as that's the only type of leaf in any of the mods that's having this issue, I'd assume it's something related to that - if I had to hazard a guess it might be something involving how Flowering/Budding Oak Leaves turn into Blossoming Oak Leaves, since the placement state isn't affected.

Relevant code for that is in com.teamaurora.fruitful.common.block.OakFlowerLeavesBlock.java, in the randomTick method. I'm not doing anything particularly wacky, just a ServerWorld.setBlockState, but it's clearly causing an issue that needs investigation lol

Attached below are a couple of images users of my mod have sent me of the issue:
![image](https://user-images.githubusercontent.com/18506935/115818582-4a41c180-a3ba-11eb-8e54-911d37051593.png)
![image](https://user-images.githubusercontent.com/18506935/115818607-5a59a100-a3ba-11eb-8e2a-925e98ad7e25.png)

**Comment by Tfarcenim** [comment]
Nothing I can do atm as a proper fix requires porting https://www.curseforge.com/minecraft/mc-mods/statement first and I simply don't have the time right now.

**Comment by Tfarcenim** [comment]
should no longer be an issue in 1.5
