### ISSUE TITLE
Mixin Crash

### ISSUE THREAD

**Issue by WenXin20** [Tfarcenim/MoreWaterlogging#7]
`Minecraft v1.16.5`
`Forge v36.1.24`
`More Waterlogging v1.5`
`Statement v4.0.1`

After installing I seem to be getting a mixin crash, although I'm unsure which other mod it is conflicting with.
[Crash Report](https://gist.github.com/WenXin20/2c42016cb3040aabe18cc00fb9f2c3d5#file-latest-log-L327)

**Comment by Tfarcenim** [comment]
Not my fault, one of the mods installed has a conflicting mixin/js coremod

**Comment by Tfarcenim** [comment]
If you find it, post it here so that others know.

**Comment by WenXin20** [comment]
This crash only happens when More Waterlogging is added to my modpack. If I remove it, the modpack works perfectly.

**Comment by Tfarcenim** [comment]
It's because more waterlogging or statement has a mixin that conflicts with another one, but that doesn't mean that more waterlogging is to blame.
There is nothing I can do on my end until the conflicting mod is at least identified.

**Comment by WenXin20** [comment]
Ok, yeah, looks like the crash is triggered by Statement and that there is also an incompatibility with FerriteCore. 
Virtuoel/Statement#5

**Comment by Tfarcenim** [comment]
Closing as resolved since it doesn't involve this mod
