### ISSUE TITLE
Invalid Vanilla Replacement

### ISSUE THREAD

**Issue by WenXin20** [Tfarcenim/MoreWaterlogging#8]
`Minecraft v1.16.5`
`Forge v36.1.32`
`More Waterlogging v1.5`
`Statement v4.0.2`

After adding this to my server with an existing world, I got an error saying that it had an invalid vanilla replacement with the anvil. I also saw the same error with the hopper. 
[Debug.log](https://gist.github.com/WenXin20/56b40c5dad50840f7a12b8aad7e69009)
[Latest.log](https://gist.github.com/WenXin20/bb6f4bf7e35e7548a51b7c9c0e5e7bf8#file-latest-log-L2783)

**Comment by Tfarcenim** [comment]
This mod conflicts with apotheosis and any other mod that uses registry replacement because it overwrites the block, nothing I can or will do about it on my end.

**Comment by WenXin20** [comment]
Ah I see, thanks. Do you know if the mods that do registry replacement can add support?

**Comment by Tfarcenim** [comment]
Maybe, I don't know.
