### ISSUE TITLE
Game crash during mod loading

### ISSUE THREAD

**Issue by Derpercoaster** [Tfarcenim/MoreWaterlogging#9]
The message I got was: More Waterlogging (morewaterlogging) encountered an error during the common_setup event phase
java.lang.IllegalStateException: null

Crash report:
[crash-2021-07-25_17.16.37-fml.txt](https://github.com/Tfarcenim/MoreWaterlogging/files/6874646/crash-2021-07-25_17.16.37-fml.txt)

**Comment by Tfarcenim** [comment]
FerriteCore crashes Statement, not my problem.
